# Project-wide Gradle settings
android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official

# Disable kapt incremental (fixes NoSuchMethodError on classpath snapshot with Kotlin 1.9.20 + Gradle 8.5)
kapt.incremental.apt=false
kapt.use.worker.api=false
